
export const USER_LOGIN = 'USER_LOGIN';

export const USER_LOGIN_API = 'USER_LOGIN_API';

export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY';

export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';

export const ADD_HISTORY = 'ADD_HISTORY';

export const OPEN_DRAWER = 'OPEN_DRAWER';

export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const OPEN_FORM = 'OPEN_FORM';

export const EDIT_PROJECT = 'EDIT_PROJECT';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const GET_USER_SEARCH = 'GET_USER_SEARCH';

export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';

export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK';

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';

export const SUBMIT_CREATE_TASK = 'SUBMIT_CREATE_TASK';

/////SAGA ACTION
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';
export const CREAT_PROJECT_SAGA = 'CREAT_PROJECT_SAGA';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const UPDATED_PROJECT_SAGA = 'UPDATED_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA'
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const ADD_USER_PROJECT_SAGA = 'ADD_USER_PROJECT_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
