
export const GET_ALL_USER_BY_PROJECT_ID = 'GET_ALL_USER_BY_PROJECT_ID';

export const GET_ALL_USER_BY_PROJECT_ID_SAGA = 'GET_ALL_USER_BY_PROJECT_ID_SAGA';

export const GET_ALL_USER = 'GET_ALL_USER';

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';

export const EDIT_USER_SAGA = 'EDIT_USER_SAGA';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const ENABLE_EDIT_CURRENT_USER = 'ENABLE_EDIT_CURRENT_USER';
export const DISABLE_EDIT_CURRENT_USER = 'DISABLE_EDIT_CURRENT_USER'